car_half_size = [2, 1]
car_radius = 1.5
car_speed = 10
car_loop_length = 100
wall_speed_hack = 1

[vehicle]
max_speed = 15
max_offroad_speed = 5
max_backward_speed = 1
acceleration = 10
auto_deceleration = 2
brake_deceleration = 30
max_rotation_speed = 1.7453292519943295
rotation_accel = 8.726646259971647
