toggle_camera = ["C"]

look_left = ["Q", "U"]
look_right = ["E", "O"]

invite_distance = 5
invite_angle = 30
invite = ["T"]
accept = ["Y"]
reject = ["N"]
phone_interact = ["P"]

[player]
accelerate = ["ArrowUp", "W"]
back = ["ArrowDown", "S"]
left = ["ArrowLeft", "A"]
right = ["ArrowRight", "D"]
stop = ["Space"]
jump = ["Digit1", "J"]
wheelie = ["Digit2", "K"]
wheelie_front = ["Digit3", "L"]
