[player]
accelerate = ["ArrowUp", "W"]
back = ["ArrowDown", "S"]
left = ["ArrowLeft", "A"]
right = ["ArrowRight", "D"]
stop = ["Space"]
jump = ["Digit1"]
wheelie = ["Digit2"]
wheelie_front = ["Digit3"]
