pixels_per_unit = 16

[waypoints]
quest_color = "yellow"
deliver_color = "blue"

[camera]
fov = 80
distance = 10
default_rotation = 20
attack_angle = 40
offset = [4, 2.5, 0]
speed = 5
auto_rotate = true
predict = 0.2
