#!/usr/bin/env bash

cd "${0%/*}"
cd ..
rm -rf assets/ui/
mkdir -p assets/ui
cd ui

npm install
npm run build
cp -r dist/assets/* ../assets/ui/.
cp -r public/* ../assets/ui/.

cd ../assets/ui
mv index*.js index.js
# listen, you really don't want to know
sed -i 's@salmoning\.js@../../salmoning.js@' index.js
mv index*.css index.css
